name: capp_flutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.7.0
  get: ^4.6.6

  device_info_plus: ^10.1.2
  android_id: ^0.4.0
  image_picker: ^1.0.1
  image_cropper: ^5.0.1
  flutter_dotenv: ^5.2.1
  flutter_slidable: ^3.0.1
  http: ^1.2.2

  # Firebase
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/lotties/
